### ISSUE TITLE
How to update the database?

### ISSUE THREAD

**Issue by glownt** [akrogp/tolomet#1]
Hi @akrogp,

I've just added a new provider in my fork of tolomet. Everything seems to be working fine however, I would like to know what is the process to generate a new version of the database. Because I have to click on "Download stations" and I have to manually download the new stations in every device where I install the fork for testing.

PD: In a future, when everyting is tested and working I'll let you know about the project and I will ask for a merge.

Best regards,
Adrián.

**Comment by akrogp** [comment]
Hi Adrián,

Here you have the steps I follow to generate a new version of the database:

1. Update the `VERSION` in class `DbTolomet`.
2. Uncomment the `updVersion()` call in `getInstance()` method of this class.
3. Run the app and download stations.
4. Using the Android Studio device explorer download the updated `Tolomet.db*` files from `/data/data/com.akrog.tolomet/databases`.
5. Merge the files using any SQLite app (I use "DB Browser for SQLite") into a single `Tolomet.db` file.
6. Copy the new `Tolomet.db` file into `tolometGui/src/main/assets/databases/`.
7. Comment the `updVersion()` call from step 2.
8. Build/run the app.

I have inherited these steps from older Android versions and probably they could be optimized now.

I look forward to hearing about your project and merging your contributions!

**Comment by glownt** [comment]
Thanks @akrogp ,
That worked like a charm. I did not have to merge the databases though. I think it's because I started with an already filled databased on my device...
I close the issue.
